### PR TITLE
Allow doctrine/collections ^2.0

### LINKED ISSUE #52: Cannot install with doctrine/collections 1.0
```bash
symfony new --webapp polyglot-test && cd polyglot-test
composer require webfactory/polyglot-bundle
```

```
Running composer update webfactory/polyglot-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - webfactory/polyglot-bundle[1.0.0, ..., 1.2.0, 2.0.0, ..., 2.1.0] require doctrine/orm ~2.2 -> found doctrine/orm[2.2.0, ..., 2.19.3] but it conflicts with your root composer.json require (^3.1).
    - webfactory/polyglot-bundle[1.1.1, ..., 1.1.3] require php ^5.5 | ^7.0 -> your php version (8.3.4) does not satisfy that requirement.
    - webfactory/polyglot-bundle[2.1.1, ..., 2.2.0] require php ^7.2 -> your php version (8.3.4) does not satisfy that requirement.
    - webfactory/polyglot-bundle[2.3.0, ..., 2.4.0] require php ^7.2|8.0.*|8.1.* -> your php version (8.3.4) does not satisfy that requirement.
    - webfactory/polyglot-bundle[2.5.0, 3.0.0, ..., 3.2.0, 4.0.0] require doctrine/collections ^1.0 -> found doctrine/collections[v1.0, ..., 1.8.0] but the package is fixed to 2.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires webfactory/polyglot-bundle * -> satisfiable by webfactory/polyglot-bundle[1.0.0, ..., 1.2.0, 2.0.0, ..., 2.5.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 4.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require webfactory/polyglot-bundle:*" to figure out if any version is installable, or "composer require webfactory/polyglot-bundle:^2.1" if you know which you need.

```

### PR DESCRIPTION
**Pull request by tacman**
fixes #52

### CODE REVIEW

**Comment by mpdude** [comment]
Heads-up @tacman, I force-pushed onto this branch to rebase it onto the current `master`.

**Comment by mpdude** [comment]
Thank you @tacman!

**Comment by tacman** [comment]
Thanks, now it's stuck or psr/log, can you approve https://github.com/webfactory/WebfactoryPolyglotBundle/pull/55

**Comment by tacman** [comment]
Also, we will need to allow doctrine/orm:^3.0 as well.

**Pull request merged**
